name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to FC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: tomii6614.web.fc2.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          local-dir: ./public/
          exclude: ignore
